
USE Northwind
GO
--ایجاد جدول کاربردی 
DROP TABLE IF EXISTS T1 
GO
CREATE TABLE T1 
(
	C1 INT ,
	C2 VARCHAR(MAX),
	C3 NVARCHAR(MAX),
	C4 VARBINARY(MAX)
)
GO
--LOB پیدا کردن دیتا تایپ های خانواده 
SELECT 
	TABLE_NAME,
	COLUMN_NAME,
	DATA_TYPE,
	CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE 
(
	DATA_TYPE IN ('TEXT','NTEXT','IMAGE') OR
	DATA_TYPE IN ('VARCHAR','NVARCHAR','VARBINARY') AND CHARACTER_MAXIMUM_LENGTH=-1
)
GO
